---
- hosts: allinone
  tasks:
  - name: Update APT package cache
    apt: update_cache=yes

  - name: Upgrade APT to the lastest packages
    apt: upgrade=safe

  - name: Install required packages
    apt: name={{item}} state=present
    with_items:
      - resolvconf
      - irqbalance
      - ubuntu-minimal
      - update-manager-core

- hosts: allinone
  tasks:
  - name: Reboot
    command: shutdown -r now
    async: 0
    poll: 0
    ignore_errors: true

  - name: Wait for SSH to come back
    local_action:
      module: wait_for
        host={{ ansible_default_ipv4.address }}
        port={{ ansible_ssh_port|default(22) }}
        delay=15
